config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root 'pages#home'
  get 'groups/search', to: 'groups#new'
  post 'groups/search', to: 'groups#search'
  get 'groups/:id/style', to: 'groups#style', as: 'group_style'
  patch 'groups/:id/style', to: 'groups#update_style'
  resources :groups
  resources :events do
    post 'set_attendance', to: 'events#set_attendance', as: 'set_attendance'
    resources :ratings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :urlname, :description, :location, :link, presence: true
  validates :urlname, uniqueness: true
  enum location: [:Sydney, :Brisbane, :Melbourne]

  has_many :events, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :style, :update_style, :update, :destroy]

  def search
    @results = MeetupService.groups(params[:search_text], params[:location])
    @group = Group.new
    render 'new'
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
  end

  def style
  end

  def update_style
    if @group.update(style_params)
      redirect_to @group, notice: 'Style succesfully added.'
    else
      render :style
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    # byebug
    @group = Group.new(group_params)
    @group.short_name = @group.name.slice(0,7) + '...'

    if @group.save
      redirect_to group_style_path(@group.id), notice: 'Group was successfully created.'
      # redirect_to @group, notice: 'Group was successfully created.'
      generate_events(@group.urlname)
    else
      redirect_to groups_path, alert: 'Group already exists.'
    end
  end

  # PATCH/PUT /groups/1
  def update
    data = MeetupService.group(@group[:urlname])
    if @group.update(name: data['name'],
                     urlname: data['urlname'],
                     description: data['description'],
                     location: data['city'],
                     link: data['link'])
      redirect_back fallback_location: root_path, notice: 'Group was successfully updated'
    else
      redirect_back fallback_location: root_path, alert: 'Failed to update group'
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :urlname, :description, :location, :link, :background_colour, :text_colour, :short_name)
    end

    def style_params
      params.require(:group).permit(:background_colour, :text_colour, :short_name)
    end

    def generate_events(urlname)
      @events = MeetupService.events(urlname)
      if @events
        @events.each do |event|
          new_event = Event.new
          new_event.group_id = @group.id
          new_event.meetup_id = event['id']
          new_event.name = event['name']
          new_event.date = Time.at(event['time']/1000).to_datetime
          new_event.description = event['description']
          new_event.last_updated = Time.at(event['updated']/1000).to_datetime
          unless new_event.save
            raise "couldn't create event"
          end
          if event['venue']
            create_venue(event['venue'], new_event.id)
          end
        end
      else
        raise 'no events found'
      end
    end

    def create_venue(venue_details, event_id)
      new_venue = Venue.new
      new_venue.event_id = event_id
      new_venue.name = venue_details['name']
      new_venue.lat = venue_details['lat']
      new_venue.lon = venue_details['lon']
      new_venue.address = venue_details['address_1']
      new_venue.city = venue_details['city']
      unless new_venue.save
        raise "couldn't create venue"
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :urlname %>
    <%= form.text_field :urlname %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.number_field :location %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="d-flex justify-content-between">
  <h1>Groups</h1>
  <%= link_to 'Add New Group', new_group_path, class: "btn btn-sm btn-success my-auto" %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th class="d-none d-md-table-cell">Description</th>
      <th class="d-none d-lg-table-cell">Meetup Link</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td class="align-middle">
          <%= link_to group.name, group %>
        </td>
        <td class="align-middle"><%= group.location %></td>
        <td class="d-none d-md-table-cell align-middle"><%= strip_tags(group.description).truncate(45, separator: ' ') %></td>
        <td class="d-none d-lg-table-cell align-middle"><%= link_to "Meetup Link", group.link %></td>
        <td class="align-middle">
          <%= link_to 'Destroy', group, class: "btn btn-sm btn-danger d-inline-block my-1", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>Add New Group</h1>
<br>
<h2>Search</h2>

<%= form_with url: groups_search_path, local: true do |form| %>
  <div class="group-search-form">
    <%= select_tag "location", options_for_select(Group.locations.keys.map {|loc| loc.titleize }), prompt: "Select Location...", class: "form-control mb-2 mr-2" %>
    <%= form.text_field :search_text, class: "form-control mb-2 mr-2", placeholder: "Search terms..." %>
    <%= form.submit 'Search', class: "btn btn-primary" %>
  </div>
<% end %>

<hr />

<% if @results %>
  <h2>Results</h2>

  <table id="results-table" class="table table-striped">
    <thead>
      <tr>
        <th>Name</td>
        <th class="group-desc">Description</td>
        <th>Meetup Link</td>
        <th>Add Group</td>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |result, index| %>
        <tr>
          <%= form_with model: @group, local: true do |form| %>
            <%= form.hidden_field :name, value: result['name'] %>
            <%= form.hidden_field :urlname, value: result['urlname'] %>
            <%= form.hidden_field :description, value: result['description'] %>
            <%= form.hidden_field :location, value: result['city'] %>
            <%= form.hidden_field :link, value: result['link'] %>
            <td class="align-middle"><%= result['name'] %></td>
            <td class="group-desc"><%= strip_tags(result['description']).truncate(45, separator: ' ') %></td>
            <td class="align-middle"><%= link_to "Meetup Link", result['link'] %></td>
            <td class="align-middle"><%= form.submit 'Add', class: "btn btn-sm py-2 px-4 btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%#= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1 class="text-center">Group Info</h1>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @group.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description.html_safe %>
</p>

<p>
  <strong>Link:</strong>
  <a href="<%= @group.link %>"><%= @group.link %></a>
</p>

<hr />

<%= link_to 'Refresh Group Details', @group, class: "btn btn-sm btn-primary d-inline-block my-1", method: :patch %>

<%= link_to 'Delete Group', @group, class: "btn btn-sm btn-danger d-inline-block my-1", method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Change Calendar Styling', group_style_path(@group), class: "btn btn-sm btn-success d-inline-block my-1" %>

app/views/groups/style.html.erb
<h2 class="my-3 text-center">Add Calendar Styling</h2>

<div class="w-25 mx-auto text-center">
  <%= form_with(model: @group, url: group_style_path(@group.id), local: true) do |form| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :short_name %>
      <%= form.text_field :short_name, class: "form-control", required: true, maxlength: 10 %>
    </div>

    <div class="form-group">
      <%= form.label :background_colour %>
      <% if @group.background_colour %>
        <%= form.color_field :background_colour, class: "form-control", required: true %>
      <% else %>
        <%= form.color_field :background_colour, value: "#FF0000", class: "form-control", required: true %>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :text_colour %>
      <% if @group.text_colour %>
        <%= form.color_field :text_colour, class: "form-control", required: true %>
      <% else %>
        <%= form.color_field :text_colour, value: "#FFFFFF", class: "form-control", required: true %>
      <% end %>
    </div>

    <h3>Preview</h3>
    <div id="group-style-preview" class="mx-auto my-3" style="background-color: <%= @group.background_colour %>; color: <%= @group.text_colour %>;"><%= @group.short_name %></div>

    <div class="form-group">
      <%= form.submit 'Submit', class: "btn btn-success form-control" %>
    </div>
  <% end %>
</div>