config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root 'pages#home'
  get 'groups/search', to: 'groups#new'
  post 'groups/search', to: 'groups#search'
  get 'groups/:id/style', to: 'groups#style', as: 'group_style'
  patch 'groups/:id/style', to: 'groups#update_style'
  resources :groups
  resources :events do
    post 'set_attendance', to: 'events#set_attendance', as: 'set_attendance'
    resources :ratings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_attending_buttons.html.erb
<div class="attending-buttons mt-2 d-flex justify-content-center">
  <%= link_to event_set_attendance_path(event.id, attending: 'going' ), method: :post do %>
    <% if attending == 'going' %>
      <i class="text-success fas fa-check mx-3"></i>
    <% else %>
      <i class="fas fa-check mx-3"></i>
    <% end %>
  <% end %>
  <%= link_to event_set_attendance_path(event.id, attending: 'not_going' ), method: :post do %>
    <% if attending == 'not_going' %>
      <i class="text-danger fas fa-times mx-3"></i>
    <% else %>
      <i class="fas fa-times mx-3"></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_event_card.html.erb
<div class="card mx-2" style="min-width: 300px">
  <% if header %>
    <div class="card-header text-center">
      <h2><%= header %></h2>
    </div>
  <% end %>
  <% if event %>
    <h2 class="card-title text-center mb-0 mt-3"><%= event.group.short_name %></h5>
    <div class="card-body">
      <p class="card-text mb-1"><%= event.name %></p>
      <p class="card-text mb-1">Date: <%= event.date.strftime("%d/%m/%Y") %></p>
      <p class="card-text mb-1">Time: <%= event.date.strftime("%l:%M%p") %></p>
      <p class="card-text mb-1">Total Going: <%#= event.total_going %></p>
      <p class="card-text mb-1">Spots Left: <%#= event.spots_left %></p>
      <p class="card-text mb-1">Hive Members Going: <%#= event.hive_going %></p>
      <%= link_to "More Details", event_path(event), class: "mb-1" %>
      <%= render 'shared/attending_buttons', event: event, attending: attending %>
    </div>
  <% else %>
    <h2 class="card-title text-center mb-0 mt-3">No Event</h5>
    <div class="card-body">
      <p class="card-text mb-1">You aren't signed up to any events.</p>
      <p class="card-text mb-1">Please choose an event from the calendar</p>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-mobile">
    <%= link_to(root_path, class: "ca-logo-link" ) do %>
      <img class="ca-logo"src="https://pbs.twimg.com/profile_images/872618954807590912/PUHHM6hV_400x400.jpg" alt="">
      <span>Hive</span>
    <% end %>
    <div id="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <ul id="nav-list">
    <% if user_signed_in? %>
      <div class="nav-left">
        <li>
          <%= link_to root_path do %>
            <i class="fas fa-home"></i> Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to events_path do %>
            <i class="fas fa-calendar-alt"></i> Events
          <% end %>
        </li>
        <li>
          <%= link_to groups_path do %>
            <i class="fas fa-users"></i> Groups
          <% end %>
        </li>
      </div>
    <% end %>

    <li id="nav-logo-mid">
      <%= link_to(root_path, class: "ca-logo-link") do %>
        <img class="ca-logo"src="https://pbs.twimg.com/profile_images/872618954807590912/PUHHM6hV_400x400.jpg" alt="">
        <span>Hive</span>
      <% end %>
    </li>

    <% if user_signed_in? %>
      <div class="nav-right">
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-user"></i> Profile
          <% end %>
        </li>
        <li>
          <%= link_to(destroy_user_session_path, method: :delete) do %>
            <i class="fas fa-sign-out-alt"></i> Logout
          <% end %>
        </li>
      </div>
    <% end %>
  </ul>
</nav>

app/views/shared/_rating_stars.html.erb
<% ratings.each do |k,v| %>
  <p class="card-text mb-1 d-flex justify-content-between" style="max-width: 170px">
    <span class="rating-label"><%= k.to_s.capitalize %>: </span>
    <span class="rating">
      <% v = 0 if v.nil? %>
      <% (5-v).times do |i| %>
        <%= link_to event_ratings_path(event.id, rating: { k => (5-i)} ), method: :post, class: "rating-star-link", "data-rating": (5-i).to_s do %>
          ☆
        <% end %>
      <% end %>
      <% v.times do |i| %>
        <%= link_to event_ratings_path(event.id, rating: { k => (v-i)} ), method: :post, class: "rating-star-link", "data-rating": (v-i).to_s do %>
          ★
        <% end %>
      <% end %>
    </span>
  </p>
<% end %>