config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root 'pages#home'
  get 'groups/search', to: 'groups#new'
  post 'groups/search', to: 'groups#search'
  get 'groups/:id/style', to: 'groups#style', as: 'group_style'
  patch 'groups/:id/style', to: 'groups#update_style'
  resources :groups
  resources :events do
    post 'set_attendance', to: 'events#set_attendance', as: 'set_attendance'
    resources :ratings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :event
  belongs_to :user

  # Creates a hash of rating values
  def to_hash
    { food: self.food, drinks: self.drinks, talks: self.talks, vibe: self.vibe }
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    # byebug
    @ratings = Rating.all
    @event = Event.find(params[:event_id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    # Check if already exists
    if Rating.find_by(user_id: current_user.id, event_id: params[:event_id])
      update
    else
      @rating = Rating.new(rating_params)
      @rating.event_id = params[:event_id]
      @rating.user_id = current_user.id

      respond_to do |format|
        if @rating.save
          format.html { redirect_back fallback_location: root_path }
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    @rating = Rating.find_by(user_id: current_user.id, event_id: params[:event_id])
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_back fallback_location: root_path }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Rating was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit("food", "drinks", "talks", "vibe")
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/index.html.erb
<h1>Ratings</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Drinks</th>
      <th>Talks</th>
      <th>Vibe</th>
      <th>Event</th>
      <th>User</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.food %></td>
        <td><%= rating.drinks %></td>
        <td><%= rating.talks %></td>
        <td><%= rating.vibe %></td>
        <td><%= rating.user.name %></td>
        <td>
          <%= link_to 'Delete', event_rating_path(rating.event.id, rating.id),
              method: :delete, class: 'btn btn-sm btn-danger',
              data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_event_rating_path %>